<img src="Brain_Gratitude.jpg
" style="float: left; margin-right: 3px;" > 

<div align="right"><h4><left><strong><span style="color:black"> "Determiner la cause et pas les symptômes."- chiraz GUESMI</span></strong></left></h4></div>

# <center>TP4 Systeme d'equations linéaires </center>
<span style='color:blue'>Réalisé par :</span>**Chiraz GUESMI** éleve ingénieur  en 2éme année téléinformatique 
<BR><span style='color:blue'>Sous la supervision de :</span> **Dr. Khemais ABDALLAH**

---------------------------------------------------------------------------------------------------------------------------


<img src="isitcom.png" style="float: left; margin-right: 3px;" > 
<img src="universiteDeSousse.png" style="float: right; margin-right: 3px;" >

<h2> Objectif :</h2>
<h2> Principes:</h2>


In [1]:
import numpy as np


In [3]:
def affiche(M):
    for i in range (len(M)):
        print(M[i])

In [4]:
def remonter(M):
    n=len(M)
    X=[0]*n
    X[n-1]=M[n-1][n]/M[n-1][n-1]
    for i in range(n-2,-1,-1):
        X[i]=M[i][n]
        for j in range (i+1,n):
            X[i]=X[i]-M[i][j]*X[j]
        X[i]=X[i]/M[i][i]
    return(X)

In [5]:
def transposition(M,L1,L2):
    X=M[L1]
    M[L1]=M[L2]
    M[L2]=X

In [6]:
def transvection (M,L1,L2,k):
    for j in range(0,len(M)+1):
        M[L2][j]=M[L2][j]+k*M[L1][j]
    

In [7]:
def lignePivotMax(M,c):
    max=M[c][c]
    indiceMax=c
    for i in range (c,len(M)):
        if M[i][c]>max:
            max=M[i][c]
            indiceMax=i
    return (indiceMax)

In [8]:
def triangulariser(M):
    for j in range(0,len(M)-1):
        numLignePivot=lignePivotMax(M,j)
        transposition(M,j,numLignePivot)
        for i in range(j+1,len(M)):
            transvection(M,j,i,-M[i][j]/M[j][j])
    return(M)


In [9]:
def pivotGauss(M):
    M=triangulariser(M)
    X=remonter(M)
    return(X)

In [10]:
n = int(input('Saisir la taille de votre Matrice A: '))
m = np.zeros((n,n+1))

for i in range(n):
    for j in range(n+1):
        m[i][j] = float(input( 'm['+str(i)+']['+ str(j)+']='))

affiche(m)


Saisir la taille de votre Matrice A: 3
m[0][0]=1
m[0][1]=2
m[0][2]=3
m[0][3]=4
m[1][0]=-1
m[1][1]=2
m[1][2]=4
m[1][3]=3
m[2][0]=1
m[2][1]=5
m[2][2]=2
m[2][3]=3
[1. 2. 3. 4.]
[-1.  2.  4.  3.]
[1. 5. 2. 3.]


In [12]:
pivotGauss(m)

[1.0, 0.0, 1.0]

In [18]:
def determinant(A):
    n = len(A)
    det = 1
    for k in range(0,n-1):
        u = A[k][k]
        det *= u
    return (det)

In [19]:
determinant(m)

4.0

 <h3> Conclusion </h3>